openapi: "3.0.0"
info:
  description: "This is a host for cargosprint public api documentation. You can use our API to search facilities and make payments. We are currently in development and will have more features coming soon. You can also visit CargoSprint's main website."
  version: "1.0.0"
  title: "CargoSprint Public Api Swagger"
  termsOfService: "https://cargosprint.com/legal/terms-of-use/sprintpay"
  contact:
    email: "support@cargosprint.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
servers:
  - url: "{scheme}://{environment}.cargosprintgroup.com"
    variables:
      scheme:
        default: "https"
        enum: ["http", "https"]
      environment:
        default: "production"
        description: "Environment API is being called. Production does not have an identifier."
tags:
  - name: "authentication"
    description: "Token needed to access service APIs"
  - name: "facility"
    description: "List facilities"
  - name: "payment"
    description: "Make payment to facility"
paths:
  /oauth2/token:
    post:
      tags:
        - "authentication"
      servers:
        - url: "{scheme}://oauth-{environment}.cargosprintgroup.com"
          variables:
            scheme:
              default: "https"
              enum: ["http", "https"]
            environment:
              description: "Environment API is being called. Production does not have an identifier."
              default: "" # Production server
              enum:
                - "" # Production server
                - develop # Development server
                - staging # Staging server
      summary: "get access token"
      operationId: "getToken"
      requestBody:
        content:
          application/json:
            schema:
              type: "object"
              properties:
                grant_type:
                  type: "string"
                  default: "client_credentials"
      responses:
        200:
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/getTokenApiResponse"
  /facilities:
    post:
      tags:
        - "facility"
      servers:
        - url: "{scheme}://facility-{environment}.cargosprintgroup.com"
          variables:
            scheme:
              default: "https"
              enum: ["http", "https"]
            environment:
              description: "Environment API is being called. Production does not have an identifier."
              default: "" # Production server
              enum:
                - "" # Production server
                - develop # Development server
                - staging # Staging server
      summary: "search for facilities"
      operationId: "searchFacilities"
      requestBody:
        content:
          application/json:
            schema:
              type: "object"
              properties:
                name:
                  type: "string"
                  description: "The name for facility"
                firmsCode:
                  type: "string"
                  description: "The code for the firm"
                airportCode:
                  type: "string"
                  description: "The code for the airline"
                airlinePrefix:
                  type: "integer"
                  format: "int64"
                  description: "The airline prefix code"
      responses:
        200:
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/searchFacilitiesResponse"
        400:
          description: "Invalid Order"
      security:
        - cargosprint_auth:
            - "api.facility:read"
  /payment:
    post:
      tags:
        - "payment"
      servers:
        - url: "{scheme}://cart-{environment}.cargosprintgroup.com"
          variables:
            scheme:
              default: "https"
              enum: ["http", "https"]
            environment:
              description: "Environment API is being called. Production does not have an identifier."
              default: "" # Production server
              enum:
                - "" # Production server
                - develop # Development server
                - staging # Staging server
      summary: "submit a payment"
      operationId: "submitPayment"
      requestBody:
        content:
          application/json:
            schema:
              type: "object"
      responses:
        200:
          description: "successful operation"
          content:
            application/json:
              schema:
                type: "object"
components:
  securitySchemes:
    cargosprint_auth:
      type: "oauth2"
      flows:
        clientCredentials:
          tokenUrl: "/oauth2/token"
          scopes:
            api.facility:read: ""
  schemas:
    getTokenApiResponse:
      type: "object"
    searchFacilitiesResponse:
      type: "object"
